### PR TITLE
Replace the access-key API command with generic dot-env commands

### PR DESCRIPTION
**Pull request by aschempp**
This allows the Contao Manager (and other API tools) to write all environment variables. Necessary to be able to e.g. add trusted proxies (#68).

FYI, changing/removing existing commands is intended and that's what the API version is for.

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]
Tests, but otherwise 👍

**Comment by aschempp** [comment]
@leofeyer is this on track to be merged? I think it still makes sense regardless if we have other .env parameters yet.

**Comment by leofeyer** [comment]
It has the "tests missing" label on it, so …

**Comment by aschempp** [comment]
Tests added and successful 😎

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
