### PR TITLE
[RTM] Fix initialize.php

### LINKED ISSUE #19: system/initialize.php file is wrong
The ```system/initialize.php``` file is wrong which causes failure of legacy extensions that depend on it. The file created by ```core-bundle``` triggers the ```AppKernel``` which does not exist, it should trigger ```ContaoKernel``` isntead.

Related issues:
https://github.com/isotope/core/issues/1771
https://github.com/codefog/contao-news_categories/issues/98

### PR DESCRIPTION
**Pull request by aschempp**
Fixes #19 

Let me know your thoughts. The code is currently untested!

### CODE REVIEW

**Comment by leofeyer** [comment]
+1 for the general concept.

I don't like the inheritance from the core bundle class, though. For instance, I was thinking about moving the command to the installation bundle, which would then break this command.

How about adding this as a separate command?

**Comment by aschempp** [comment]
Well the other option would be just to call the core command similar to what I do with the web-dir command…

**Comment by leofeyer** [comment]
Why can't this be a separate command just like `contao:install-web-dir`? You could execute it here then:

https://github.com/contao/manager-bundle/blob/develop/src/Composer/ScriptHandler.php#L40

**Comment by aschempp** [comment]
It appears rather stupid to me to require a second method call just to fix the installation? In my opinion a `contao:install` call should set up everything, from system folder to initialize.php and entry points in one call, otherwise the application will not work correctly anyway…

**Comment by leofeyer** [comment]
Then we should dispatch an event or use tagged services. The current solution is bad package design and tightly couples the manager-bundle to the installation-bundle for no reason.

**Comment by Toflar** [comment]
Imho you should use the `ConsoleTerminateEvent` for that 😄

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
